# install nodeJS
- name: install nodeJS engine
  remote_user: root
  hosts: vm-3
  pre_tasks:
  - name: update system (may take a while)
    apt: update_cache=yes

  - name: install packages
    apt: pkg=nodejs

#  - name: ensure services are running
#    service: name={{ item }} state=started enabled=yes
#    with_items:
#    - node

#  - name: wait for ghost to be up
#    wait_for: port=80 delay=10

  post_tasks:
  - name: finished
    debug: msg="setup of node done on {{ vm.default_ip }}"
#    debug: msg='Open your browser http://{{ vm.default_ip }}'
