---
- name: mariadb container
  docker:
    name: mariadb
    image: mariadb/5
    state: started
    volumes:
    - mydata
    env:
      MYSQL_ROOT_PASSWORD: djMucnRen5G5

- name: wordpress container
  docker:
    name: wordpress
    image: wordpress/fpm
    state: reloaded
    pull: always
    volumes:
    - /var/www/html
    links:
    - "mariadb:mysql"

- name: nginx container
  docker:
    name: nginx
    image: nginx
    state: reloaded
    volumes_from:
    - wordpress
    links:
    - "wordpress:wordpress"
    ports:
    - "80:80"
    - "443:443"