---
- name: install latest nodeJS repo
  shell: curl -sL https://deb.nodesource.com/setup_5.x | bash -

- name: update system (may take a while)
  apt: update_cache=yes

- name: install nodeJS
  apt: pkg={{ item }}
  with_items:
    - nodejs