---
- name: create data folders
#command: mkdir -p /home/wp/db /home/wp/data /home/wp/conf
  file: path={{ item }} state=directory
  with_items:
    - /home/wp/db
    - /home/wp/data
#    - /home/wp/conf

#- name: copy nginx conf
#  template: src=nginx.conf.j2 dest=/home/wp/conf/nginx.conf

# deploy containers
- name: mariadb container
  docker:
    name: mariadb
    image: mariadb:5
    state: started
    volumes:
      - /home/wp/db:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: djMucnRen5G5

- name: wordpress container
  docker:
    name: wordpress
    image: wordpress
    state: reloaded
    pull: always
    volumes:
      - /home/wp/data:/var/www/html
    links:
      - "mariadb:mysql"

#- name: nginx container
#  docker:
#    name: nginx
#    image: nginx
#    state: reloaded
#    volumes:
#      - /home/wp/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#    volumes_from:
#      - wordpress
#    links:
#      - "wordpress:wordpress"
#    ports:
#      - "80:80"